name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
